trigger:
- master
- release/*

# Run PR validation on all branches
pr:
  autoCancel: true
  branches:
    include:
    - master
    - release/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  Configuration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install Net Core'
  inputs:
    useGlobalJson: true
    packageType: sdk

- task: DotNetCoreCLI@1
  displayName: 'Restore NuGet Packages'
  inputs:
    command: restore
    projects: '**/*.csproj'

- script: | 
    dotnet build --configuration $(Configuration)
    dotnet test tests --configuration $(Configuration) --logger trx

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
